Solution of language basics-1
tavisca-bootcamp/language-basics-01 pull request #68
Opened 2019-06-23 17:14 UTC by tavisca-tkatyal

@tavisca-vtripathi

2019-06-23 17:14 UTC, tavisca-tkatyal commented
@tavisca-vtripathi

2019-06-26 11:38 UTC, tavisca-vtripathi requested changes

2019-06-26 11:38 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +            string A = equation.Substring(0,prev);
use a proper naming convention. Rename `**A**` to a meaningful variable name

2019-06-26 11:38 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +            string B = equation.Substring(prev+1,next-prev-1);
Use the proper naming convention. 
 Rename **B**

https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md

2019-06-26 11:38 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +            string C = equation.Substring(next+1);
Same as above

2019-06-26 11:38 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +        {
**`Create another Class FixMultiplication and create new method FindDigit there.`**

 And from Class Program's method Find Digit, call the method of FixMultiplication

2019-06-27 12:22 UTC, tavisca-tkatyal commented
@tavisca-vtripathi 
Changes done

2019-06-29 13:51 UTC, tavisca-vtripathi requested changes

2019-06-29 13:51 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +                float a = float.Parse(A);
what is float a? how it is different from A?

Can give some meaningful name to it.

2019-06-29 13:51 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +            if(C.Contains('?'))
We are checking the same conditions in If and elseif. can we put it in a method and do the calling from here?

2019-06-29 13:51 UTC, tavisca-vtripathi commented on Tavisca.Bootcamp.LanguageBasics.Exercise1/Program.cs
> +                float res = a*b;
user complete name, not an abbreviation.

2019-06-29 19:12 UTC, closed without merging